name = "aiken-extra/string_util"
version = "3.200.202409"
license = "Apache-2.0"
description = "An Aiken utility library to pretty-print data"

[repository]
user = "aiken-extra"
project = "string_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"
